"""add_rfc_numero_cuenta

Revision ID: 39318a879b1d
Revises: eeeca86a00aa
Create Date: 2026-08-09 21:45:09.781616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '39318a879b1d'
down_revision: Union[str, None] = 'eeeca86a00aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alumnos', sa.Column('numero_cuenta', sa.String(), nullable=True))
    op.create_index(op.f('ix_alumnos_numero_cuenta'), 'alumnos', ['numero_cuenta'], unique=True)
    op.add_column('users', sa.Column('rfc', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_rfc'), 'users', ['rfc'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_rfc'), table_name='users')
    op.drop_column('users', 'rfc')
    op.drop_index(op.f('ix_alumnos_numero_cuenta'), table_name='alumnos')
    op.drop_column('alumnos', 'numero_cuenta')
    # ### end Alembic commands ###