"""initial_schema

Revision ID: eeeca86a00aa
Revises: 
Create Date: 2026-08-09 21:09:44.226969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'eeeca86a00aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingenieria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingenieria_clave'), 'ingenieria', ['clave'], unique=True)
    op.create_index(op.f('ix_ingenieria_id'), 'ingenieria', ['id'], unique=False)
    op.create_index(op.f('ix_ingenieria_nombre'), 'ingenieria', ['nombre'], unique=False)
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permission_created_at'), 'permission', ['created_at'], unique=False)
    op.create_index(op.f('ix_permission_id'), 'permission', ['id'], unique=False)
    op.create_index(op.f('ix_permission_name'), 'permission', ['name'], unique=False)
    op.create_index(op.f('ix_permission_updated_at'), 'permission', ['updated_at'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_created_at'), 'role', ['created_at'], unique=False)
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=False)
    op.create_index(op.f('ix_role_updated_at'), 'role', ['updated_at'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=False),
    sa.Column('correo_personal', sa.String(), nullable=False),
    sa.Column('correo_institucional', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('auth_method', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_apellido_materno'), 'users', ['apellido_materno'], unique=False)
    op.create_index(op.f('ix_users_apellido_paterno'), 'users', ['apellido_paterno'], unique=False)
    op.create_index(op.f('ix_users_correo_institucional'), 'users', ['correo_institucional'], unique=True)
    op.create_index(op.f('ix_users_correo_personal'), 'users', ['correo_personal'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nombre'), 'users', ['nombre'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ingenieria_id', sa.Integer(), nullable=False),
    sa.Column('numero_folio', sa.String(), nullable=True),
    sa.Column('periodo_ingreso', sa.String(), nullable=False),
    sa.Column('promedio_bachillerato', sa.Float(), nullable=True),
    sa.Column('indice_uaem', sa.Float(), nullable=True),
    sa.Column('lugar_admision', sa.Integer(), nullable=True),
    sa.Column('escuela_procedencia', sa.String(), nullable=True),
    sa.Column('tiene_internet', sa.Boolean(), nullable=True),
    sa.Column('tiene_computadora', sa.Boolean(), nullable=True),
    sa.Column('vulnerabilidad_economica', sa.Boolean(), nullable=True),
    sa.Column('es_foraneo', sa.Boolean(), nullable=True),
    sa.Column('convivencia', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingenieria_id'], ['ingenieria.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alumnos_convivencia'), 'alumnos', ['convivencia'], unique=False)
    op.create_index(op.f('ix_alumnos_es_foraneo'), 'alumnos', ['es_foraneo'], unique=False)
    op.create_index(op.f('ix_alumnos_escuela_procedencia'), 'alumnos', ['escuela_procedencia'], unique=False)
    op.create_index(op.f('ix_alumnos_id'), 'alumnos', ['id'], unique=False)
    op.create_index(op.f('ix_alumnos_indice_uaem'), 'alumnos', ['indice_uaem'], unique=False)
    op.create_index(op.f('ix_alumnos_ingenieria_id'), 'alumnos', ['ingenieria_id'], unique=False)
    op.create_index(op.f('ix_alumnos_lugar_admision'), 'alumnos', ['lugar_admision'], unique=False)
    op.create_index(op.f('ix_alumnos_numero_folio'), 'alumnos', ['numero_folio'], unique=True)
    op.create_index(op.f('ix_alumnos_periodo_ingreso'), 'alumnos', ['periodo_ingreso'], unique=False)
    op.create_index(op.f('ix_alumnos_promedio_bachillerato'), 'alumnos', ['promedio_bachillerato'], unique=False)
    op.create_index(op.f('ix_alumnos_tiene_computadora'), 'alumnos', ['tiene_computadora'], unique=False)
    op.create_index(op.f('ix_alumnos_tiene_internet'), 'alumnos', ['tiene_internet'], unique=False)
    op.create_index(op.f('ix_alumnos_usuario_id'), 'alumnos', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_alumnos_vulnerabilidad_economica'), 'alumnos', ['vulnerabilidad_economica'], unique=False)
    op.create_table('examenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('total_preguntas', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=True),
    sa.Column('fecha_cierre', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examenes_creado_por_id'), 'examenes', ['creado_por_id'], unique=False)
    op.create_index(op.f('ix_examenes_fecha_aplicacion'), 'examenes', ['fecha_aplicacion'], unique=False)
    op.create_index(op.f('ix_examenes_fecha_cierre'), 'examenes', ['fecha_cierre'], unique=False)
    op.create_index(op.f('ix_examenes_id'), 'examenes', ['id'], unique=False)
    op.create_index(op.f('ix_examenes_periodo'), 'examenes', ['periodo'], unique=False)
    op.create_index(op.f('ix_examenes_titulo'), 'examenes', ['titulo'], unique=False)
    op.create_table('asignacion_examen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('asignado_por', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['asignado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('examen_id', 'alumno_id', name='uq_examen_alumno')
    )
    op.create_index(op.f('ix_asignacion_examen_alumno_id'), 'asignacion_examen', ['alumno_id'], unique=False)
    op.create_index(op.f('ix_asignacion_examen_examen_id'), 'asignacion_examen', ['examen_id'], unique=False)
    op.create_index(op.f('ix_asignacion_examen_id'), 'asignacion_examen', ['id'], unique=False)
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('examen_id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('total_preguntas', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['examen_id'], ['examenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modulos_clave'), 'modulos', ['clave'], unique=True)
    op.create_index(op.f('ix_modulos_examen_id'), 'modulos', ['examen_id'], unique=False)
    op.create_index(op.f('ix_modulos_id'), 'modulos', ['id'], unique=False)
    op.create_index(op.f('ix_modulos_nombre'), 'modulos', ['nombre'], unique=False)
    op.create_index(op.f('ix_modulos_orden'), 'modulos', ['orden'], unique=False)
    op.create_index(op.f('ix_modulos_total_preguntas'), 'modulos', ['total_preguntas'], unique=False)
    op.create_table('intento_presentacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.Column('intento_num', sa.Integer(), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('puntaje_total', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('puntaje_algebra', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('puntaje_trigonometria', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('puntaje_geometria', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('puntaje_calculo', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('estado', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignacion_examen.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asignacion_id', 'intento_num', name='uq_intento_presentacion_asignacion_num')
    )
    op.create_index(op.f('ix_intento_presentacion_asignacion_id'), 'intento_presentacion', ['asignacion_id'], unique=False)
    op.create_table('preguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('enunciado', sa.Text(), nullable=True),
    sa.Column('opcion_a', sa.Text(), nullable=True),
    sa.Column('opcion_b', sa.Text(), nullable=True),
    sa.Column('opcion_c', sa.Text(), nullable=True),
    sa.Column('opcion_d', sa.Text(), nullable=True),
    sa.Column('respuesta_correcta', sa.String(length=1), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preguntas_codigo'), 'preguntas', ['codigo'], unique=False)
    op.create_index(op.f('ix_preguntas_id'), 'preguntas', ['id'], unique=False)
    op.create_index(op.f('ix_preguntas_modulo_id'), 'preguntas', ['modulo_id'], unique=False)
    op.create_index(op.f('ix_preguntas_orden'), 'preguntas', ['orden'], unique=False)
    op.create_index(op.f('ix_preguntas_respuesta_correcta'), 'preguntas', ['respuesta_correcta'], unique=False)
    op.create_table('asignacion_modulo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intento_id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('puntaje', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('correctas', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['intento_id'], ['intento_presentacion.id'], ),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intento_id', 'modulo_id', name='uq_asignacion_modulo_intento_modulo')
    )
    op.create_index(op.f('ix_asignacion_modulo_intento_id'), 'asignacion_modulo', ['intento_id'], unique=False)
    op.create_index(op.f('ix_asignacion_modulo_modulo_id'), 'asignacion_modulo', ['modulo_id'], unique=False)
    op.create_table('feedback_resultado',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intento_id', sa.Integer(), nullable=False),
    sa.Column('feedback_general', sa.Text(), nullable=True),
    sa.Column('feedback_algebra', sa.Text(), nullable=True),
    sa.Column('feedback_trigonometria', sa.Text(), nullable=True),
    sa.Column('feedback_geometria', sa.Text(), nullable=True),
    sa.Column('feedback_calculo', sa.Text(), nullable=True),
    sa.Column('nivel_desempeno', sa.Integer(), nullable=True),
    sa.Column('recomendacion', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('generado_en', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['intento_id'], ['intento_presentacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_resultado_intento_id'), 'feedback_resultado', ['intento_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_resultado_intento_id'), table_name='feedback_resultado')
    op.drop_table('feedback_resultado')
    op.drop_index(op.f('ix_asignacion_modulo_modulo_id'), table_name='asignacion_modulo')
    op.drop_index(op.f('ix_asignacion_modulo_intento_id'), table_name='asignacion_modulo')
    op.drop_table('asignacion_modulo')
    op.drop_index(op.f('ix_preguntas_respuesta_correcta'), table_name='preguntas')
    op.drop_index(op.f('ix_preguntas_orden'), table_name='preguntas')
    op.drop_index(op.f('ix_preguntas_modulo_id'), table_name='preguntas')
    op.drop_index(op.f('ix_preguntas_id'), table_name='preguntas')
    op.drop_index(op.f('ix_preguntas_codigo'), table_name='preguntas')
    op.drop_table('preguntas')
    op.drop_index(op.f('ix_intento_presentacion_asignacion_id'), table_name='intento_presentacion')
    op.drop_table('intento_presentacion')
    op.drop_index(op.f('ix_modulos_total_preguntas'), table_name='modulos')
    op.drop_index(op.f('ix_modulos_orden'), table_name='modulos')
    op.drop_index(op.f('ix_modulos_nombre'), table_name='modulos')
    op.drop_index(op.f('ix_modulos_id'), table_name='modulos')
    op.drop_index(op.f('ix_modulos_examen_id'), table_name='modulos')
    op.drop_index(op.f('ix_modulos_clave'), table_name='modulos')
    op.drop_table('modulos')
    op.drop_index(op.f('ix_asignacion_examen_id'), table_name='asignacion_examen')
    op.drop_index(op.f('ix_asignacion_examen_examen_id'), table_name='asignacion_examen')
    op.drop_index(op.f('ix_asignacion_examen_alumno_id'), table_name='asignacion_examen')
    op.drop_table('asignacion_examen')
    op.drop_index(op.f('ix_examenes_titulo'), table_name='examenes')
    op.drop_index(op.f('ix_examenes_periodo'), table_name='examenes')
    op.drop_index(op.f('ix_examenes_id'), table_name='examenes')
    op.drop_index(op.f('ix_examenes_fecha_cierre'), table_name='examenes')
    op.drop_index(op.f('ix_examenes_fecha_aplicacion'), table_name='examenes')
    op.drop_index(op.f('ix_examenes_creado_por_id'), table_name='examenes')
    op.drop_table('examenes')
    op.drop_index(op.f('ix_alumnos_vulnerabilidad_economica'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_usuario_id'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_tiene_internet'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_tiene_computadora'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_promedio_bachillerato'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_periodo_ingreso'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_numero_folio'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_lugar_admision'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_ingenieria_id'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_indice_uaem'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_id'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_escuela_procedencia'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_es_foraneo'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_convivencia'), table_name='alumnos')
    op.drop_table('alumnos')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_nombre'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_correo_personal'), table_name='users')
    op.drop_index(op.f('ix_users_correo_institucional'), table_name='users')
    op.drop_index(op.f('ix_users_apellido_paterno'), table_name='users')
    op.drop_index(op.f('ix_users_apellido_materno'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_role_updated_at'), table_name='role')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_index(op.f('ix_role_created_at'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_permission_updated_at'), table_name='permission')
    op.drop_index(op.f('ix_permission_name'), table_name='permission')
    op.drop_index(op.f('ix_permission_id'), table_name='permission')
    op.drop_index(op.f('ix_permission_created_at'), table_name='permission')
    op.drop_table('permission')
    op.drop_index(op.f('ix_ingenieria_nombre'), table_name='ingenieria')
    op.drop_index(op.f('ix_ingenieria_id'), table_name='ingenieria')
    op.drop_index(op.f('ix_ingenieria_clave'), table_name='ingenieria')
    op.drop_table('ingenieria')
    # ### end Alembic commands ###